from fpdf import FPDF
import json
import os
import uuid
from datetime import datetime

class ClinicalPDF(FPDF):
    """Professional clinical-grade PDF generator for Nidaan.ai EHR reports."""
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=25)
    
    def header(self):
        # Top accent bar
        self.set_fill_color(16, 163, 127)
        self.rect(0, 0, 210, 3, 'F')
        
        # Logo
        self.set_font('helvetica', 'B', 18)
        self.set_text_color(16, 163, 127)
        self.set_y(10)
        self.cell(0, 10, 'NIDAAN.ai', ln=0)
        
        # Subtitle
        self.set_font('helvetica', '', 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, 'AI-Powered Health Intelligence Report', ln=1, align='R')
        
        # Line
        self.set_draw_color(220, 220, 220)
        self.line(10, 22, 200, 22)
        self.ln(15)

    def footer(self):
        self.set_y(-20)
        self.set_draw_color(220, 220, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font('helvetica', '', 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 8, f'Page {self.page_no()}/{{nb}}', align='L')
        self.cell(0, 8, 'Generated by NIDAAN.ai | For medical reference only', align='R', ln=1)

    def section_title(self, title, color=(16, 163, 127)):
        self.ln(4)
        self.set_fill_color(*color)
        self.rect(10, self.get_y(), 3, 8, 'F')
        self.set_x(16)
        self.set_font('helvetica', 'B', 11)
        self.set_text_color(30, 30, 30)
        self.cell(0, 8, self._safe(title), ln=1)
        self.ln(2)

    def info_row(self, label, value):
        self.set_font('helvetica', 'B', 9)
        self.set_text_color(100, 100, 100)
        self.cell(50, 7, self._safe(label), ln=0)
        self.set_font('helvetica', '', 9)
        self.set_text_color(30, 30, 30)
        self.cell(0, 7, self._safe(str(value)), ln=1)

    def body_text(self, text):
        self.set_font('helvetica', '', 9)
        self.set_text_color(50, 50, 50)
        clean = text.replace('**', '').replace('###', '').replace('##', '').replace('#', '').replace('- ', '  . ')
        self.multi_cell(0, 5.5, self._safe(clean))

    def write_markdown(self, markdown_text):
        """Advanced theme-aware markdown parser for professional PDF generation"""
        lines = str(markdown_text).split('\n')
        
        current_theme = 'neutral'
        
        for line in lines:
            line = line.strip()
            if not line:
                self.ln(3)
                continue
            
            # Semantic theme detection based on headers
            if line.startswith('#'):
                lower_line = line.lower()
                if any(w in lower_line for w in ['worsen', 'decline', 'concern', 'bad', 'risk']):
                    current_theme = 'negative'
                elif any(w in lower_line for w in ['improv', 'recover', 'benefit', 'good']):
                    current_theme = 'positive'
                elif any(w in lower_line for w in ['precaution', 'watch', 'monitor']):
                    current_theme = 'warning'
                elif any(w in lower_line for w in ['recommend', 'consult', 'doctor']):
                    current_theme = 'info'
                else:
                    current_theme = 'neutral'

                level = len(line) - len(line.lstrip('#'))
                text = line.lstrip('#').strip().replace('**', '')
                self.ln(2)
                
                # Assign colors based on theme
                if current_theme == 'negative':
                    r, g, b = (220, 38, 38) # Red
                elif current_theme == 'positive':
                    r, g, b = (16, 163, 127) # Green
                elif current_theme == 'warning':
                    r, g, b = (245, 158, 11) # Orange/Amber
                elif current_theme == 'info':
                    r, g, b = (59, 130, 246) # Blue
                else:
                    if level == 1:
                        r, g, b = (16, 163, 127)
                    elif level == 2:
                        r, g, b = (59, 130, 246)
                    else:
                        r, g, b = (139, 92, 246) # Purple

                if level == 1:
                    self.set_font('helvetica', 'B', 12)
                elif level == 2:
                    self.set_font('helvetica', 'B', 11)
                else:
                    self.set_font('helvetica', 'B', 10)
                
                self.set_text_color(r, g, b)
                self.cell(0, 6, self._safe(text), ln=1)
                self.ln(1)
                continue
            
            # Handle bullet points contextually
            is_bullet = False
            if line.startswith('- ') or line.startswith('* '):
                is_bullet = True
                self.set_x(14)
                self.set_font('helvetica', 'B', 11)
                
                if current_theme == 'negative':
                    self.set_text_color(220, 38, 38)
                    self.cell(4, 5, self._safe('-'), ln=0)
                elif current_theme == 'positive':
                    self.set_text_color(16, 163, 127)
                    self.cell(4, 5, self._safe('+'), ln=0)
                elif current_theme == 'warning':
                    self.set_text_color(245, 158, 11)
                    self.cell(4, 5, self._safe('!'), ln=0)
                else:
                    self.set_text_color(59, 130, 246)
                    self.cell(4, 5, self._safe('\u2022'), ln=0)
                    
                line = line[2:].strip()
            elif line[0:1].isdigit() and line[1:3] == '. ':
                is_bullet = True
                self.set_x(14)
                self.set_font('helvetica', 'B', 9)
                self.set_text_color(59, 130, 246)
                self.cell(6, 5, self._safe(line[:2]), ln=0)
                line = line[3:].strip()
            
            # Split by ** and toggle bold
            parts = line.split('**')
            for i, part in enumerate(parts):
                if not part: continue
                if i % 2 == 1:
                    # Bold inline
                    self.set_font('helvetica', 'B', 9)
                    self.set_text_color(30, 30, 30)
                else:
                    # Normal inline
                    self.set_font('helvetica', '', 9)
                    self.set_text_color(70, 70, 70)
                
                self.write(5, self._safe(part))
            
            self.ln(5.5) # newline after the paragraph
            if is_bullet:
                self.set_x(10)

    def _safe(self, text):
        """Encode text safely for latin-1 PDF output."""
        return str(text).encode('latin-1', 'replace').decode('latin-1')


def generate_pdf_from_json(raw_json: dict, markdown_summary: str, output_path: str):
    pdf = ClinicalPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Extract metadata ──
    patient = raw_json.get("patient_details", {})
    metadata = raw_json.get("report_metadata", {})
    pages = raw_json.get("pages", [])
    
    patient_name = patient.get("name", "Not available")
    patient_age = patient.get("age", "N/A")
    patient_gender = patient.get("gender", "N/A")
    
    lab_name = metadata.get("lab_name", "Not mentioned in report")
    referring_doctor = metadata.get("referring_doctor", "Not mentioned in report")
    actual_test_date = metadata.get("actual_test_date", "Not available")
    report_gen_date = metadata.get("report_generation_date", "Not available")

    # ── Report Information ──
    pdf.section_title('REPORT INFORMATION')
    pdf.info_row('Original Test Date:', actual_test_date)
    pdf.info_row('Report Generated:', report_gen_date)
    pdf.info_row('AI Analysis Date:', datetime.now().strftime('%B %d, %Y at %I:%M %p'))
    pdf.info_row('Classification:', 'Confidential — Patient Use Only')
    pdf.ln(2)

    # ── Source Information ──
    pdf.section_title('SOURCE INFORMATION', color=(59, 130, 246))
    pdf.info_row('Laboratory / Clinic:', lab_name)
    pdf.info_row('Referring Doctor:', referring_doctor)
    pdf.ln(2)

    # ── Patient Information ──
    pdf.section_title('PATIENT INFORMATION', color=(139, 92, 246))
    pdf.info_row('Patient Name:', patient_name)
    pdf.info_row('Age:', patient_age)
    pdf.info_row('Gender:', patient_gender)
    pdf.ln(2)

    # ── Biomarker Analysis (Page by Page) ──
    for page_data in pages:
        page_num = page_data.get("page_number", "?")
        categories = page_data.get("test_categories_on_page", [])
        results = page_data.get("lab_results", [])
        
        if not results:
            continue
        
        cat_label = ", ".join(categories) if categories else "Medical Tests"
        pdf.section_title(f'PAGE {page_num}: {cat_label}', color=(245, 158, 11))
        
        # Table header
        col_w = [58, 22, 18, 38, 20]  # test, result, unit, ref range, status
        pdf.set_fill_color(240, 240, 245)
        pdf.set_font('helvetica', 'B', 7.5)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(col_w[0], 8, '  Parameter', border=0, fill=True)
        pdf.cell(col_w[1], 8, 'Result', border=0, fill=True)
        pdf.cell(col_w[2], 8, 'Unit', border=0, fill=True)
        pdf.cell(col_w[3], 8, 'Reference Range', border=0, fill=True)
        pdf.cell(col_w[4], 8, 'Status', border=0, fill=True, ln=1)
        
        pdf.set_font('helvetica', '', 7.5)
        
        for i, r in enumerate(results):
            # Zebra stripe
            if i % 2 == 0:
                pdf.set_fill_color(252, 252, 252)
            else:
                pdf.set_fill_color(247, 247, 247)
            
            test_name = pdf._safe(str(r.get('test_name', 'Unknown'))[:30])
            result_val = pdf._safe(str(r.get('result', 'N/A'))[:12])
            unit = pdf._safe(str(r.get('unit', ''))[:10])
            ref_range = pdf._safe(str(r.get('reference_range', '-'))[:22])
            status = str(r.get('status', 'Normal'))
            
            # Color-code the status
            pdf.set_text_color(50, 50, 50)
            pdf.cell(col_w[0], 7, f'  {test_name}', border=0, fill=True)
            pdf.cell(col_w[1], 7, result_val, border=0, fill=True)
            pdf.cell(col_w[2], 7, unit, border=0, fill=True)
            pdf.cell(col_w[3], 7, ref_range, border=0, fill=True)
            
            # Status with color
            if status.lower() in ('high', 'critical'):
                pdf.set_text_color(220, 38, 38)  # Red
                pdf.set_font('helvetica', 'B', 7.5)
            elif status.lower() == 'low':
                pdf.set_text_color(245, 158, 11)  # Orange
                pdf.set_font('helvetica', 'B', 7.5)
            else:
                pdf.set_text_color(16, 163, 127)  # Green
                pdf.set_font('helvetica', '', 7.5)
            
            status_symbol = {'high': '↑ HIGH', 'low': '↓ LOW', 'critical': '⚠ CRITICAL', 'normal': '✓ NORMAL'}.get(status.lower(), status)
            pdf.cell(col_w[4], 7, pdf._safe(status_symbol), border=0, fill=True, ln=1)
            
            pdf.set_text_color(50, 50, 50)
            pdf.set_font('helvetica', '', 7.5)
        
        pdf.ln(3)

    # ── AI Summary ──
    if markdown_summary:
        pdf.section_title('AI DIAGNOSTIC SUMMARY', color=(16, 163, 127))
        pdf.body_text(markdown_summary)

    # ── Disclaimer ──
    pdf.ln(8)
    pdf.set_fill_color(255, 250, 240)
    y_before = pdf.get_y()
    pdf.rect(10, y_before, 190, 20, 'F')
    pdf.set_font('helvetica', 'I', 7)
    pdf.set_text_color(180, 130, 60)
    pdf.set_x(14)
    pdf.multi_cell(182, 4,
        'DISCLAIMER: This report was generated by NIDAAN.ai using artificial intelligence. '
        'It is intended for informational purposes only and does not constitute medical advice. '
        'Always consult a qualified healthcare professional for diagnosis and treatment decisions. '
        'Original test data sourced from the uploaded medical report.'
    )

    pdf.output(output_path)
    return output_path


def generate_progress_pdf(progress_data: dict, output_path: str):
    """Generate a professional PDF for the health progress analysis report."""
    # ── Sanitize all fields defensively ──
    def safe_int(v, default=0):
        try: return int(float(v))
        except: return default
    def safe_float(v, default=0):
        try: return float(v)
        except: return default
    def safe_list(v):
        if isinstance(v, list): return v
        if isinstance(v, str) and v: return [v]
        return []
    def safe_str(v):
        if v is None: return ''
        return str(v)

    earliest   = safe_int(progress_data.get('earliest_severity', 0))
    latest     = safe_int(progress_data.get('latest_severity', 0))
    improvement = safe_float(progress_data.get('improvement_percentage', 0))
    improvements = safe_list(progress_data.get('key_improvements', []))
    concerns     = safe_list(progress_data.get('key_concerns', []))
    date_range   = safe_str(progress_data.get('date_range', 'N/A'))
    reports_cnt  = safe_int(progress_data.get('reports_analyzed', 0))
    summary      = safe_str(progress_data.get('progress_summary', ''))
    refs         = safe_list(progress_data.get('report_references', []))

    pdf = ClinicalPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Title Banner ──
    pdf.set_fill_color(16, 163, 127)
    pdf.rect(10, pdf.get_y(), 190, 14, 'F')
    pdf.set_font('helvetica', 'B', 13)
    pdf.set_text_color(255, 255, 255)
    pdf.set_x(16)
    pdf.cell(0, 14, pdf._safe('HEALTH PROGRESS ANALYSIS REPORT'), ln=1)
    pdf.ln(6)

    # ── Period & Count ──
    pdf.section_title('ANALYSIS OVERVIEW')
    pdf.info_row('Period Covered:', date_range)
    pdf.info_row('Reports Analyzed:', str(reports_cnt))
    pdf.ln(3)

    # ── Report References ──
    if refs:
        pdf.section_title('REPORTS INCLUDED IN ANALYSIS', color=(139, 92, 246))
        for ref in refs:
            pdf.set_font('helvetica', 'B', 9)
            pdf.set_text_color(30, 30, 30)
            date_str = ref.get('test_date', '')
            pdf.cell(30, 6, pdf._safe(f"Report {ref.get('index', '')}:"), ln=0)
            
            pdf.set_font('helvetica', '', 9)
            pdf.set_text_color(70, 70, 70)
            pdf.cell(25, 6, pdf._safe(date_str), ln=0)
            
            # Combine Doc and Lab
            doc = ref.get('doctor_name', '')
            lab = ref.get('lab_name', '')
            details = []
            if doc and doc.lower() not in ['not specified', 'unknown', 'na', 'n/a']:
                details.append(f"Dr. {doc.replace('Dr. ', '').strip()}")
            if lab and lab.lower() not in ['not mentioned in report', 'unknown lab', 'unknown']:
                details.append(f"Lab: {lab}")
                
            details_str = " | ".join(details) if details else ref.get('report_title', 'Medical Report')
            pdf.cell(0, 6, pdf._safe(details_str), ln=1)
        pdf.ln(3)

    # ── Severity Score Comparison ──
    pdf.section_title('SEVERITY SCORE COMPARISON', color=(59, 130, 246))

    col_w = [63, 63, 64]
    # Header row
    pdf.set_fill_color(240, 240, 245)
    pdf.set_font('helvetica', 'B', 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(col_w[0], 10, '  Initial Severity', border=0, fill=True)
    pdf.cell(col_w[1], 10, '  Current Severity', border=0, fill=True)
    pdf.cell(col_w[2], 10, '  Overall Change', border=0, fill=True, ln=1)
    # Values row
    pdf.set_fill_color(250, 250, 252)
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(*(220, 38, 38) if earliest > 50 else (16, 163, 127))
    pdf.cell(col_w[0], 14, f'  {earliest}/100', border=0, fill=True)
    pdf.set_text_color(*(220, 38, 38) if latest > 50 else (16, 163, 127))
    pdf.cell(col_w[1], 14, f'  {latest}/100', border=0, fill=True)
    pdf.set_text_color(*(16, 163, 127) if improvement >= 0 else (220, 38, 38))
    sign = '+' if improvement >= 0 else ''
    pdf.cell(col_w[2], 14, f'  {sign}{int(improvement)}%', border=0, fill=True, ln=1)
    pdf.set_text_color(50, 50, 50)
    pdf.ln(5)

    # ── Full AI Analysis ──
    if summary:
        pdf.section_title('HEALTH PROGRESSION DETAILS', color=(14, 165, 233))
        pdf.write_markdown(summary)

    # ── Disclaimer ──
    pdf.ln(8)
    pdf.set_fill_color(255, 250, 240)
    y_before = pdf.get_y()
    if y_before > 260:
        pdf.add_page()
        y_before = pdf.get_y()
    pdf.rect(10, y_before, 190, 20, 'F')
    pdf.set_font('helvetica', 'I', 7)
    pdf.set_text_color(180, 130, 60)
    pdf.set_x(14)
    pdf.multi_cell(182, 4,
        'DISCLAIMER: This progress report was generated by NIDAAN.ai using artificial intelligence. '
        'It is intended for informational purposes only and does not constitute medical advice. '
        'Always consult a qualified healthcare professional for diagnosis and treatment decisions.'
    )

    pdf.output(output_path)
    return output_path
